"""add_rule_type_and_threshold_fields_to_correlation_rules

Revision ID: 0ebdbffeb671
Revises: a853be681492
Create Date: 2025-06-01 16:22:58.082756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ebdbffeb671'
down_revision: Union[str, None] = 'a853be681492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('correlation_rules', sa.Column('rule_type', sa.Enum('IOC_MATCH_IP', 'THRESHOLD_LOGIN_FAILURES', 'THRESHOLD_DATA_EXFILTRATION', name='correlation_rule_type_enum_db', native_enum=False), nullable=False))
    op.add_column('correlation_rules', sa.Column('threshold_count', sa.Integer(), nullable=True))
    op.add_column('correlation_rules', sa.Column('threshold_time_window_minutes', sa.Integer(), nullable=True))
    op.add_column('correlation_rules', sa.Column('aggregation_fields', sa.ARRAY(sa.Enum('SOURCE_IP', 'DESTINATION_IP', 'USERNAME', 'HOSTNAME', 'EVENT_MESSAGE', 'NETWORK_BYTES_TOTAL', name='aggregation_event_field_enum_db', native_enum=False)), nullable=True))
    op.alter_column('correlation_rules', 'event_field_to_match',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('SOURCE_IP', 'DESTINATION_IP', 'USERNAME', 'HOSTNAME', 'EVENT_MESSAGE', 'NETWORK_BYTES_TOTAL', name='event_field_match_type_enum_db', native_enum=False),
               nullable=True)
    op.alter_column('correlation_rules', 'ioc_type_to_match',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('correlation_rules', 'ioc_type_to_match',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
    op.alter_column('correlation_rules', 'event_field_to_match',
               existing_type=sa.Enum('SOURCE_IP', 'DESTINATION_IP', 'USERNAME', 'HOSTNAME', 'EVENT_MESSAGE', 'NETWORK_BYTES_TOTAL', name='event_field_match_type_enum_db', native_enum=False),
               type_=sa.VARCHAR(length=14),
               nullable=False)
    op.drop_column('correlation_rules', 'aggregation_fields')
    op.drop_column('correlation_rules', 'threshold_time_window_minutes')
    op.drop_column('correlation_rules', 'threshold_count')
    op.drop_column('correlation_rules', 'rule_type')
    # ### end Alembic commands ###
