"""create_ioc_sources_table

Revision ID: 1c4deb0c6fec
Revises: 1c6164fff533
Create Date: 2025-05-31 12:43:37.818408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4deb0c6fec'
down_revision: Union[str, None] = '1c6164fff533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ioc_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('MISP', 'OPENCTI', 'STIX_FEED', 'CSV_URL', 'INTERNAL', name='ioc_source_type_enum_db', native_enum=False), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_fetched', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ioc_sources_id'), 'ioc_sources', ['id'], unique=False)
    op.create_index(op.f('ix_ioc_sources_name'), 'ioc_sources', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ioc_sources_name'), table_name='ioc_sources')
    op.drop_index(op.f('ix_ioc_sources_id'), table_name='ioc_sources')
    op.drop_table('ioc_sources')
    # ### end Alembic commands ###
