"""create_response_actions_and_pipelines_tables

Revision ID: 88848fa89488
Revises: 0ebdbffeb671
Create Date: 2025-06-01 21:20:00.243173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88848fa89488'
down_revision: Union[str, None] = '0ebdbffeb671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('BLOCK_IP', 'UNBLOCK_IP', 'SEND_EMAIL', 'CREATE_TICKET', 'ISOLATE_HOST', name='response_action_type_enum_db', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_response_actions_id'), 'response_actions', ['id'], unique=False)
    op.create_table('response_pipelines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('trigger_correlation_rule_id', sa.Integer(), nullable=True),
    sa.Column('actions_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['trigger_correlation_rule_id'], ['correlation_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_response_pipelines_id'), 'response_pipelines', ['id'], unique=False)
    op.create_index(op.f('ix_response_pipelines_trigger_correlation_rule_id'), 'response_pipelines', ['trigger_correlation_rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_pipelines_trigger_correlation_rule_id'), table_name='response_pipelines')
    op.drop_index(op.f('ix_response_pipelines_id'), table_name='response_pipelines')
    op.drop_table('response_pipelines')
    op.drop_index(op.f('ix_response_actions_id'), table_name='response_actions')
    op.drop_table('response_actions')
    # ### end Alembic commands ###
