"""create_initial_tables

Revision ID: a780f02cbea3
Revises: 
Create Date: 2025-05-29 22:14:15.487984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a780f02cbea3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('encrypted_password', sa.String(), nullable=False),
    sa.Column('device_type', sa.Enum('MIKROTIK_ROUTEROS', name='device_type_enum_db'), nullable=False),
    sa.Column('status', sa.Enum('REACHABLE', 'UNREACHABLE', 'ERROR', 'CONFIGURING', 'UNKNOWN', name='device_status_enum_db'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('last_successful_connection', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('syslog_configured_by_siem', sa.Boolean(), nullable=False),
    sa.Column('netflow_configured_by_siem', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host')
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_name'), 'devices', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_name'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
