"""create_correlation_rules_and_offences_tables

Revision ID: a853be681492
Revises: b6330182912f
Create Date: 2025-06-01 11:42:50.518149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a853be681492'
down_revision: Union[str, None] = 'b6330182912f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlation_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('event_source_type', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('event_field_to_match', sa.Enum('SOURCE_IP', 'DESTINATION_IP', name='event_field_match_type_enum_db', native_enum=False), nullable=False),
    sa.Column('ioc_type_to_match', sa.Enum('IPV4_ADDR', 'IPV6_ADDR', name='ioc_type_match_enum_db', native_enum=False), nullable=False),
    sa.Column('ioc_tags_match', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ioc_min_confidence', sa.Integer(), nullable=True),
    sa.Column('generated_offence_title_template', sa.String(), nullable=False),
    sa.Column('generated_offence_severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='offence_severity_enum_db', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_correlation_rules_id'), 'correlation_rules', ['id'], unique=False)
    op.create_table('offences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='offence_severity_enum_db', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'CLOSED_FALSE_POSITIVE', 'CLOSED_TRUE_POSITIVE', 'CLOSED_OTHER', name='offence_status_enum_db', native_enum=False), nullable=False),
    sa.Column('correlation_rule_id', sa.Integer(), nullable=False),
    sa.Column('triggering_event_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matched_ioc_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attributed_apt_group_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offences_id'), 'offences', ['id'], unique=False)
    op.alter_column('ioc_sources', 'type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('MISP', 'OPENCTI', 'STIX_FEED', 'CSV_URL', 'INTERNAL', 'MOCK_APT_REPORT', name='ioc_source_type_enum_db', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ioc_sources', 'type',
               existing_type=sa.Enum('MISP', 'OPENCTI', 'STIX_FEED', 'CSV_URL', 'INTERNAL', 'MOCK_APT_REPORT', name='ioc_source_type_enum_db', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.drop_index(op.f('ix_offences_id'), table_name='offences')
    op.drop_table('offences')
    op.drop_index(op.f('ix_correlation_rules_id'), table_name='correlation_rules')
    op.drop_table('correlation_rules')
    # ### end Alembic commands ###
