"""create_apt_groups_table

Revision ID: b6330182912f
Revises: 1c4deb0c6fec
Create Date: 2025-05-31 18:44:19.855334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6330182912f'
down_revision: Union[str, None] = '1c4deb0c6fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apt_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('aliases', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sophistication', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'UNKNOWN', name='apt_sophistication_enum_db', native_enum=False), nullable=True),
    sa.Column('primary_motivation', sa.Enum('ESPIONAGE', 'FINANCIAL_GAIN', 'SABOTAGE', 'HACKTIVISM', 'UNKNOWN', name='apt_motivation_enum_db', native_enum=False), nullable=True),
    sa.Column('target_sectors', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('first_observed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_observed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('references', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apt_groups_id'), 'apt_groups', ['id'], unique=False)
    op.create_index(op.f('ix_apt_groups_name'), 'apt_groups', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apt_groups_name'), table_name='apt_groups')
    op.drop_index(op.f('ix_apt_groups_id'), table_name='apt_groups')
    op.drop_table('apt_groups')
    # ### end Alembic commands ###
